services:
  deno-server:
    image: pierrecabriere/dynamic-deno-server:1.2.1
    ports:
      - '9999:9999'
    volumes:
      - ./supabase/functions:/opt/functions
    environment:
      - HEALTH_CHECK_ATTEMPTS=10
      - WATCH_FILES=true
      - CHECK_CODE=false
      - DEBUG=*
      - PUBLIC_DENO_SUPABASE_URL=${PUBLIC_DENO_SUPABASE_URL}
      - PUBLIC_DENO_SUPABASE_SERVICE_ROLE_KEY=${PUBLIC_DENO_SUPABASE_SERVICE_ROLE_KEY}
      - PUBLIC_DENO_OPENAI_API_KEY=${PUBLIC_DENO_OPENAI_API_KEY}
    restart: unless-stopped
